# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Enviar bom dia no \#geral

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Download fonts
      run: |
        mkdir assets
        cd assets
        wget -O charlotte_5.zip https://dl.dafont.com/dl/?f=charlotte_5
        wget -O Ubuntu.zip https://fonts.google.com/download?family=Ubuntu
        unzip charlotte_5.zip
        unzip Ubuntu.zip
    - name: Gerar Imagem
      run: java -jar target/BomDiaGenerator-1.0-SNAPSHOT.jar
    - name: Enviar Imagem
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: bom-dia.png
    
